# to run as fullnode
version: '3.8'

services:
   core:
     image: terrarebirth/core:ubuntu.22.04
     build:
      context: .
      dockerfile: Dockerfile.core
      platforms:
        - "linux/amd64"
      labels:
        - "description=Contains bare opzd binary"
   fullnode:
     image: terrarebirth/fullnode:ubuntu.22.04
     build: 
      context: .
      dockerfile: Dockerfile.node
      args:
        base_image: terrarebirth/core
        version: ubuntu.22.04
      platforms:
        - "linux/amd64"
      labels:
        - "description=Contains for run a full node"
